### ISSUE TITLE
CertificateVerificationTask: regions meaning

### ISSUE THREAD

**Issue by AloisHofstaetter** [BRZ-GmbH/CovidCertificate-SDK-Android#1]
Hi

I would like to know the meaning of the regions in CertificateVerificationTask.
I could not find it somewhere.
ET: Entry
NG: Night Club (Nachtgastro)
BG: ?

Thank you!

**Comment by martinreichart** [comment]
See the rule schema here https://github.com/eu-digital-green-certificates/dgc-gateway/blob/main/src/main/resources/validation-rule.schema.json
The region is meant to further distinguish different rulesets for a single country. You guessed ET and NG correctly. BG is the Occupational Group Test = Berufsgruppentest

**Comment by AloisHofstaetter** [comment]
Thank you very much!
